// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "bootstrap/dist/css/bootstrap.min.css";
// import "./globals.css";
// import Header from "@/components/Header/header";
// import Footer from "@/components/Footer/footer";
// import WhatsappButton from "@/components/WhatsAppButton/WhatsappButton";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "OnTrack Soluções",
//   description: "Generated by create next app",
//   icons: {
//     icon: "/favicon.png",
//   },
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable}`}>
//         <Header />
//         {children}
//         <Footer />
//         <WhatsappButton />
//       </body>
//     </html>
//   );
// }

"use client";
import maintenance from "@/assets/lotties/maintenance.json";
import Lottie from "lottie-react";

export default function RootLayout() {
  return (
    <html lang="en">
      <body
        style={{
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
          height: "100vh",
          margin: 0,
          backgroundColor: "#fff",
        }}
      >
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            textAlign: "center",
          }}
        >
          <div style={{ width: 800, maxWidth: "90vw" }}>
            <Lottie animationData={maintenance} loop={true} />
          </div>
          <h1 style={{ marginTop: 20 }}>Site em manutenção</h1>
        </div>
      </body>
    </html>
  );
}
